[tool.poetry]
name = "tetris"
version = "0.1.0"
description = ""
authors = ["spaceofmiah <geek_200@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pyinstaller = "^5.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
